from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
import os


information = """

Kendrick Lamar Duckworth (born June 17, 1987) is an American rapper. Regarded as one of the greatest rappers of all time, he was awarded the 2018 Pulitzer Prize for Music, becoming the first musician outside of the classical and jazz genres to receive the honor.

Born in Compton, California, Lamar began releasing music under the stage name K.Dot while attending high school. He signed with Top Dawg Entertainment (TDE) in 2005, and co-founded the hip hop supergroup Black Hippy there. Following the 2011 release of his alternative rap debut album Section.80, Lamar secured a joint contract with Dr. Dre's Aftermath Entertainment and Interscope Records. He rose to prominence with his gangsta rap-influenced second album Good Kid, M.A.A.D City (2012), which became the longest-charting hip hop studio album in Billboard 200 history; Rolling Stone named it the greatest concept album of all time. In 2015, Lamar scored his first Billboard Hot 100 number-one single, after featuring on the remix of Taylor Swift's "Bad Blood", and released his third album, To Pimp a Butterfly, which infused hip-hop with historical African-American music genres such as jazz, funk, and soul, and became his first of five consecutive number-one albums on the Billboard 200 chart.

Lamar's critical and commercial success continued with his R&B and pop-leaning fourth album Damn (2017), yielding his second US number-one single, "Humble". He curated original songs for the soundtrack of the 2018 film Black Panther, earning a nomination for the Academy Award for Best Original Song for the US top-ten single "All the Stars". His Mr. Morale & the Big Steppers (2022) double album concluded his tenure with TDE and Aftermath. His 2024 feud with Drake spawned the US number-ones "Like That" and "Not Like Us", with the latter winning a joint-record five Grammy Awards, including Song of the Year and Record of the Year. His sixth album, GNX (2024), produced his fifth US number-one single, "Squabble Up".

Lamar has received various accolades, including 22 Grammy Awards (the third-most won by a rapper), a Primetime Emmy Award, a Brit Award, 4 American Music Awards, 7 Billboard Music Awards, 11 MTV Video Music Awards (including 2 Video of the Year wins), and a record 37 BET Hip Hop Awards. Time listed him as one of the 100 most influential people in the world in 2016. Three of his works were included in Rolling Stone's 2020 revision of the 500 Greatest Albums of All Time. His Super Bowl LIX halftime show in 2025 broke viewership records, with 133.5 million viewers domestically. Outside of music, Lamar co-founded the creative company PGLang and ventured into film with his longtime creative partner, Dave Free.

Early life
Kendrick Lamar Duckworth was born on June 17, 1987, in Compton, California.[1] He is the first child of former gang hustler Kenneth "Kenny" Duckworth and hairdresser Paula Oliver. Both of his parents are African Americans from the South Side of Chicago.[2] When they were teenagers, they relocated to Compton in 1984, due to his father's affiliation with the Gangster Disciples.[3] Lamar was named after singer-songwriter Eddie Kendricks of the Temptations.[4] He was an only child until the age of seven and was described as a loner by his mother.[2][5] Eventually, his parents had his two younger brothers and younger sister, businesswoman Kayla Sawyer (née Duckworth).[6] His cousins include basketball player Nick Young and rapper Baby Keem.[7][8]

Lamar and his family lived in Section 8 housing, were reliant on welfare and food stamps, and experienced homelessness.[9][10] Although he is not a member of a particular gang, he grew up with close affiliates of the Westside Pirus.[3] Despite suffering hardships, Lamar remembered having "good memories" of his childhood that sparked his interest in hip hop music, such as sneaking into his parents' house parties.[2][11] He was raised secular, although he occasionally attended church services and was taught the Bible by his grandmother.[12] He felt "spiritually unsatisfied" as a child due to the "empty" and "one-sided" nature of the sermons.[13]

After hearing a recording of his voice for the first time, Lamar became interested in rapping.[14] He was introduced to police brutality after experiencing the first day of the 1992 Los Angeles riots.[2] When he was five years old, he witnessed a murder for the first time while sitting outside of his apartment unit, as a teenage drug dealer was killed in a drive-by shooting.[2] "It done [sic] something to me right then and there," Lamar later admitted to NPR Music. "It let me know that this is not only something that I'm looking at, but it's something that maybe I have to get used to."[15] His parents nicknamed him "Man-Man" due to his precocious behavior, although he confessed it "put a stigma on the idea of me reacting as a kid sometimes—I would hurt myself and they would expect me not to cry."[16]

In school, Lamar was a quiet and observant student who excelled academically and had a noticeable stutter.[17] His first grade teacher at Robert E. McNair Elementary School encouraged him to become a writer after she heard him correctly use the word "audacity".[18] As a seventh grade student at Vanguard Learning Center, Lamar was introduced to poetry by his English teacher, Regis Inge.[19] Inge integrated the literary form into his curriculum as a response to the growing racial tensions amongst his students. Through its connection to hip hop, Lamar studied rhymes, metaphors and double entendres, which made him fall in love with songwriting: "You can put all your feelings down on a sheet of paper, and they'd make sense to you. I liked that."[2][19] Instead of completing assignments for other classes, Lamar would scribe lyrics in his notebooks.[19] His initial writing was entirely profane, but it helped him manage his psychological trauma and depression, which he struggled with during his adolescence.[19][20] Inge played a vital role in his intellectual growth, often critiquing his lexicon and suggesting prompts to strengthen his prose.[19]

Lamar later attended Centennial High School.[21] He was enrolled in summer school during the tenth grade, which he dreaded because it forced him to be embroiled in a gang war.[21] Despite his efforts to avoid them, Lamar soon became heavily involved with Compton's hedonistic gang culture, which led to numerous health scares and encounters with the police.[2] He distanced himself from the lifestyle following an intervention staged by his father.[5] When he was 16, Lamar was baptized and converted to Christianity following the death of a friend.[22][23] He graduated from high school in 2005 as a straight-A student.[24][25] He considered studying psychology and astronomy in college, but suspended his academic pursuits to focus on his music career.[2][26]

Career
2003–2008: Beginnings

Lamar began his career while he attended Centennial High School
During high school, Lamar adopted the stage name K.Dot and began freestyling and battle rapping at school.[27] His performances caught the attention of fellow student Dave Free, who traveled from Inglewood to watch him rap.[27] They quickly formed a friendship over their love of hip-hop and the television sitcom Martin.[27] They recorded music together at Free's makeshift garage studio and at his older brother's Hyde Park apartment.[27] Lamar's earliest performances were held at a "super hood" comedy club and behind a tattoo parlor.[27] Free was his hype man during that time, while his older brother was his manager and disc jockey.[27] Lamar recorded five mixtapes throughout the 2000s; his first, Youngest Head Nigga in Charge (Hub City Threat: Minor of the Year), was released on April 15, 2003, through Konkrete Jungle Musik.[28] The mixtapes primarily consisted of freestyles over the production of popular hip-hop songs.[28]

In a series of retrospective reviews for Rolling Stone, Mosi Reeves complimented Lamar's "unerring" sense of rhythm and timing found in Hub City Threat: Minor of the Year, but criticized his "clumsy" lyricism and that his flow was "overly beholden to ... Jay-Z and Lil Wayne".[28] Free, who was working as a computer technician, introduced the mixtape to record producer Anthony "Top Dawg" Tiffith while attempting to repair his computer.[29] Tiffith was impressed with Lamar's burgeoning abilities and invited him to partake in an audition process for entry into his newly established independent record label, Top Dawg Entertainment (TDE).[29] During his audition, Lamar freestyled for Tiffith and record executive Terrence "Punch" Henderson for two hours, a strategy that impressed Henderson but bewildered Tiffith.[5][30] He was offered a recording contract by TDE in 2005, joining Jay Rock as the label's first signings.[5] Upon signing, he purchased a minority stake in the label for an undisclosed amount.[30]

Lamar had a brief stint as a security guard when he started working on music with Jay Rock at TDE's in-house recording studio.[31][25] The bond he formed with him, Ab-Soul and Schoolboy Q led to the formation of the hip-hop supergroup, Black Hippy.[32] Lamar released his second mixtape, Training Day, on December 30, 2005.[28] Reeves complemented its varied production and "well-executed" concept, which was based on the 2001 film.[28] In 2006, Lamar signed an artist development deal with Def Jam Recordings and was featured on two singles by the Game. He also heavily contributed to Jay Rock's first two mixtapes, Watts Finest Vol. 1 and Watts Finest Vol. 2: The Nickerson Files.[16][33] Lamar was ultimately let go from Def Jam after an encounter with its president and chief executive officer, Jay-Z; he later described it as "one of those situations where I wasn't ready."[34][35] Lamar and Jay Rock released a collaborative mixtape, title No Sleep 'til NYC, on December 24, 2007.[28] Reeves thought the project was a "fun cypher session, nothing more, nothing less."[28]

2009–2011: Overly Dedicated and Section.80
Lamar's third mixtape C4, released on January 30, 2009, is a tribute project to Lil Wayne's Tha Carter III (2008) and was supported by his co-sign.[36] Reeves felt that the mixtape was a "wrongheaded homage to a year-old, well-worn album."[28] From February to July, he toured with the Game on his LAX Tour as a hype man for Jay Rock.[37][38] Lamar disliked how his stage name diverted attention away from his true identity, and decided to retire it.[39] He opted to use his first and middle names professionally and regards the name change as part of his career growth.[40] For his eponymous debut extended play (2009),[41] Lamar eschewed the creative process of his mixtapes in favor of a project heavily focused on his songwriting over "lovely yet doleful" production.[28] Reeves described the EP as the "first standout project" of his career, praising its melancholic tone.[28] He felt that the project restored his reputation following the sting of criticism he received over C4.[28]


Lamar performing at Sound Academy in 2011, prior to the release of Section.80
After striking a music publishing deal with Warner/Chappell Music,[42] Lamar released his fourth mixtape, Overly Dedicated, on September 14, 2010. It was his first project to be purchased through digital retailers.[43] Reeves described Overly Dedicated as a partial "victory lap" that marked a shift in his songwriting.[28] The mixtape peaked at number 72 on Billboard's Top R&B/Hip-Hop Albums chart.[44] Lamar served as Jay Rock's hype man for a second time during Tech N9ne's Independent Grind Tour, where Overly Dedicated was introduced to Dr. Dre.[45][46] After watching the music video for the song "Ignorance Is Bliss" on YouTube, he reached out to Lamar with hopes of working with him and Snoop Dogg on his unfinished album, Detox.[45][47] He also considered signing him to his record label, Aftermath Entertainment, and was encouraged to by artists such as J. Cole.[48][49]

Lamar entered a brief relationship with Nitty Scott,[50][51] and was featured on XXL's 2011 Freshman Class list.[52] He released his debut studio album, Section.80, on July 2, 2011,[53] which was supported by its lead single "HiiiPower".[54] The album explored conscious and alternative hip-hop styles and experimented with "stripped-down" jazz production.[55][56] Ogden Payne of Forbes considers it to be "the genesis to [Lamar] successfully balancing social commentary with mass appeal."[57] Section.80 marked Lamar's first appearance on the Billboard 200 chart, where it peaked at number 113. It sold approximately 5,000 copies in its first week of tracking, with minimal coverage from mainstream media outlets.[58] To promote the album, Lamar performed at small venues and college campuses across the U.S.[59][60] He was dubbed the "New King of the West Coast" by Snoop Dogg, Dr. Dre and the Game during a performance in West Los Angeles.[61][62] Throughout the year, he appeared on the Game's The R.E.D. Album, Tech N9ne's All 6's and 7's, 9th Wonder's The Wonder Years, and Drake's Take Care.[63]

2012–2013: Good Kid, M.A.A.D City

Lamar performing at the Pitchfork Music Festival in 2012
Lamar began planning his second album before Section.80 was released.[64] From February to April 2012, he opened for Drake on his Club Paradise Tour.[65] He began working with J. Cole on a collaborative album around that time.[66][67] On March 8, The Fader reported that Lamar had signed a joint venture recording contract with Aftermath Entertainment and Interscope Records; under the deal, TDE continued to serve as his primary label.[68] His first commercial single, "The Recipe" featuring Dr. Dre, premiered on rhythmic crossover radio on April 2.[69]

Good Kid, M.A.A.D City, Lamar's second album and first under a major record label, was released on October 22, 2012.[70][71] He worked with producers such as Pharrell Williams, Hit-Boy, Scoop DeVille, Jack Splash, and T-Minus to create an atmospheric West Coast hip-hop album with heavy gangsta rap influences.[72] Its lead single, "Swimming Pools (Drank)",[73] marked Lamar's first top 20 single on the U.S. Billboard Hot 100.[74] Its other singles, "Backseat Freestyle", "Poetic Justice", and "Bitch, Don't Kill My Vibe", enjoyed moderate commercial success.[75][76] Good Kid, M.A.A.D City was met with widespread critical acclaim, who lauded Lamar's nonlinear songwriting and thematic scope. Greg Kot of the Chicago Tribune applauded him for giving gangsta tropes a "twist, or sometimes upend[ing] them completely" on a record that "brims with comedy, complexity and the many voices in [Lamar's] head."[77] The album debuted at number two on the Billboard 200 with 242,000 copies sold;[78] the highest first-week album sales of the year by a male rapper.[79] Good Kid, M.A.A.D City surpassed The Eminem Show (2002) to become the longest-charting hip-hop studio album on the Billboard 200.[80] In October 2022, it became the first hip-hop studio album to spend over ten consecutive years on the chart.[81]

From September to October 2012, Lamar headlined the BET Music Matters Tour with Black Hippy and Stalley.[82] He won Lyricist of the Year at the BET Hip Hop Awards,[83] and was featured on ASAP Rocky's single "Fuckin' Problems" alongside Drake and 2 Chainz, which reached the top 10 in the U.S.[84] Lamar embarked on two headlining concert tours in 2013: a national college tour with Steve Aoki and his first international tour.[85][86] He struggled with depression, survivor's guilt and suicidal ideation during promotional events upon learning of the deaths of three close friends.[87] From October to December 2013, Lamar opened for Kanye West on his Yeezus Tour, despite disapproval from his label and management team.[88][89] He was baptized for a second time during the beginning of the tour, and experienced a nervous breakdown near the end.[90][91] Lamar won three awards each during the BET Awards and BET Hip Hop Awards,[92][93] including Best New Artist at the former.[94][95]

Lamar was featured on six songs throughout the year: "YOLO" by the Lonely Island featuring Adam Levine,[96] the remix of "How Many Drinks?" by Miguel,[97] "Collard Greens" by Schoolboy Q,[98] "Control" with Big Sean and Jay Electronica,[99] "Give It 2 U" by Robin Thicke featuring 2 Chainz,[100] and "Love Game" by Eminem.[101] His performance on "Control" was described as a "wake up call" for the hip-hop industry and commenced his decade-long feud with Drake.[102] Rolling Stone noted that his verse made the track one of the most important hip-hop songs of the last decade.[103] Lamar was named Rapper of the Year by GQ during their annual Men of the Year edition.[104] Following the issue's release, Tiffith pulled him from performing at GQ's accompanying party and accused Steve Marsh's profile on him of containing "racial overtones".[105][106]

2014–2016: To Pimp a Butterfly and Untitled Unmastered
After his opening stint for the Yeezus Tour ended, Lamar started working on his third album.[89] He earned seven nominations at the 56th Annual Grammy Awards (January 2014), including Best New Artist, Best Rap Album, and Album of the Year for Good Kid, M.A.A.D City.[107] He was winless at the ceremony, which several media outlets felt was a snub.[108][109] Macklemore, who won Best New Artist and Best Rap Album, shared a text message that he sent Lamar after the ceremony ended, in which he apologized for winning over him.[110] The incident was the subject of widespread media attention, controversy and Internet memes.[111] During the awards ceremony, Lamar performed a mashup of "M.A.A.D City" and "Radioactive" with rock band Imagine Dragons, which was met with critical acclaim.[112][113]

Lamar opened for Eminem on the Rapture Tour from February to July 2014.[114][115] On August 9, he premiered the short film M.A.A.D, which he starred in, commissioned and produced, during the Sundance Institute's Next Fest.[116] He released "I" as the lead single to his third album, To Pimp a Butterfly, on September 23, which won Best Rap Performance and Best Rap Song at the 57th Annual Grammy Awards.[117][118] His performance of "I" during his appearance as a musical guest on Saturday Night Live was lauded by contemporary critics.[119] Lamar was featured on three songs in 2014: "It's On Again" by Alicia Keys,[120] "Babylon" by SZA,[121] and "Never Catch Me" by Flying Lotus.[122] He won Lyricist of the Year for the second consecutive time at the BET Hip Hop Awards.[123]


Lamar at the Hollywood Palladium before the 57th Annual Grammy Awards (2015), where he won Best Rap Performance and Best Rap Song for "I"
Originally scheduled to arrive at a later date, To Pimp a Butterfly was released on March 15, 2015.[124] The album incorporated various genres synonymous with African American music, such as jazz, funk, and soul.[125] To capture its essence, Lamar recruited producers such as Sounwave, Pharrell Williams, Terrace Martin, and Thundercat.[126] Whitney Alford, Lamar's fianceé, contributed background vocals on select tracks.[127] Other singles from the album were "The Blacker the Berry",[128] "King Kunta",[129] "Alright", and "These Walls"–all of which enjoyed moderate commercial success.[130] Selling 324,000 copies in its first week, To Pimp a Butterfly became Lamar's first number-one album on the Billboard 200 and the UK Albums Chart.[131][132] Billboard commented that "twenty years ago, a conscious rap record wouldn't have penetrated the mainstream in the way [Lamar] did with To Pimp a Butterfly. His sense of timing is impeccable. In the midst of rampant cases of police brutality and racial tension across America, he spews raw, aggressive bard while possible cutting a rug."[133] Pitchfork opined that the album "forced critics to think deeply about music."[134]

He earned his first number-one single in the U.S. through the remix of singer-songwriter Taylor Swift's "Bad Blood".[135][136] It won Video of the Year and Best Collaboration at the MTV Video Music Awards, while the music video for "Alright" won Best Direction.[137] Lamar later re-recorded his featured appearance on the "Bad Blood" remix in support of Swift's counteraction to her masters dispute.[138][139] He opened the BET Awards with a controversial performance of "Alright" and won Best Male Hip Hop Artist.[140] He also won three awards at the BET Hip Hop Awards.[141] In support of To Pimp a Butterfly, Lamar embarked on the Kunta's Groove Sessions Tour, which ran from October to November 2015 in select intimate venues across the U.S.[142] For his work on the album and other collaborations throughout the year, Lamar earned 11 nominations at the 58th Annual Grammy Awards, the most by a rapper in a single night.[143] He led the winners with five awards: To Pimp a Butterfly was named Best Rap Album, "Alright" won Best Rap Performance and Best Rap Song, "These Walls" won Best Rap/Sung Performance, and "Bad Blood" won Best Music Video.[144]

During the ceremony, Lamar performed a critically acclaimed medley of "The Blacker the Berry", "Alright", and an untitled song.[145] He previously performed untitled songs on The Colbert Report (December 2014) and The Tonight Show Starring Jimmy Fallon (January 2016).[146][147] After receiving a request from basketball player LeBron James to share the untitled works, Lamar released his first compilation album, Untitled Unmastered, on March 4, 2016.[148] It contained eight untitled, dated, unfinished, and entirely self-written tracks that were intended to be included on To Pimp a Butterfly, and continued the album's exploration of jazz, funk, soul, and avant-garde styles.[149] Untitled Unmastered received critical acclaim and debuted atop the Billboard 200 with 178,000 album-equivalent units, becoming Lamar's second consecutive number-one project.[150] Throughout the year, he was featured on four commercially successful songs: Beyoncé's "Freedom",[151] Maroon 5's "Don't Wanna Know",[152][153] the Weeknd's "Sidewalks",[154] and Travis Scott's "Goosebumps".[155]

2017–2019: Damn and Black Panther: The Album

Lamar on The Damn Tour (2017)
On March 1, 2017, during a cover story for T, Lamar confirmed that he was working on his fourth album, Damn.[156] He released the promotional single "The Heart Part 4" on March 23, before releasing the album's lead single "Humble" on March 30.[157][158] The song debuted at number two on the Hot 100 and reached the top spot in its second week of charting. It is Lamar's second single, and first as a lead artist, to top the chart.[159] Damn was released on April 14.[160] It utilized a more mainstream musical palette than To Pimp a Butterfly, exploring R&B and pop elements.[161] Rolling Stone described its sonics as a "brilliant combination of the timeless and the modern, the old school and the next-level."[162] Damn became Lamar's most commercially successful album. It spent four non-consecutive weeks atop the Billboard 200, marking his third consecutive number-one album, and debuted with 603,000 units sold.[163][164] All of the album's 14 songs debuted on the Hot 100, including the top-20 singles "Loyalty" and "Love".[165] Damn was the seventh best-selling album of 2017, according to the International Federation of the Phonographic Industry (IFPI), while "Humble" was the sixth best-selling single of the year.[166] By June 2018, it became the first album by a rapper or solo artist to have every song featured earn a gold certification or higher from the Recording Industry Association of America.[167]

To support Damn, Lamar embarked on his first headlining arena tour, the Damn Tour, from July 2017 to July 2018.[168] It grossed $62.7 million in worldwide revenue, becoming one of the highest-grossing hip-hop tours in history.[169] At the 2017 MTV Video Music Awards, Lamar opened the ceremony with a performance of "DNA" and "Humble".[170] He later won five awards, including Best Hip Hop Video, Best Direction, and Video of the Year for "Humble"; the latter win marked the first time an artist won the prize for a video they co-directed.[171][172] Throughout the year, he was featured on the remix to Future's "Mask Off",[173] SZA's "Doves in the Wind",[174][175] and Rich the Kid's "New Freezer".[176] He won Best Male Hip Hop Artist at the BET Awards,[177] while Damn won Favorite Rap/Hip Hop Album at the American Music Awards.[178] A collector's edition of the album, which featured its tracklist in reverse order, was released in December.[179][180]

On January 4, 2018, Lamar announced that he would be curating and executive producing Black Panther: The Album, the soundtrack from the 2018 film.[181] It was released on February 9 and was supported with three commercially successful singles: "All the Stars",[182] "King's Dead",[183] and "Pray for Me".[184][185] Lamar contributed lead and background vocals to every track on the album, regardless of credit, and produced on select songs.[186][187] Music critics consider Black Panther: The Album to be a milestone achievement, giving praise towards its lyrics and cultural significance.[188][189] It spent two consecutive weeks atop the Billboard 200,[190] and earned the most single-week streams for a soundtrack album in history.[191] Lamar opened the 60th Annual Grammy Awards with a critically acclaimed medley.[192] He won five awards during the ceremony: Damn was named Best Rap Album, "Humble" won Best Rap Performance, Best Rap Song, and Best Music Video and "Loyalty" won Best Rap/Sung Performance.[193] Damn won the Pulitzer Prize for Music on April 16, 2018, marking the first time a musical composition outside of the classical and jazz genres received the honor.[194][195]

From May to June 2018, Lamar co-headlined the Championship Tour with several TDE artists.[196][197] While on tour, he became embroiled in a public dispute with Spotify regarding the streaming service's Hate Content & Hateful Conduct policy.[198][199] Lamar was featured on five songs throughout the year: "Dedication" by Nipsey Hussle,[200][201] "Mona Lisa" by Lil Wayne,[202] "Tints" by Anderson .Paak,[203][204] and "Wow Freestyle" by Jay Rock; he also executive produced the latter's album Redemption.[205][206] At the American Music Awards, Black Panther: The Album won Favorite Rap/Hip-Hop Album.[207] Lamar made his acting debut as a drug addict in the crime drama series Power (2018).[208] After his two concert tours ended, he entered a four-year recording hiatus;[209] although he contributed to Beyoncé's The Lion King: The Gift, Schoolboy Q's Crash Talk, and Sir's Chasing Summer (all 2019).[210][211] As his publishing deal with Warner/Chappell Music was beginning to expire,[42] Lamar signed a long-term worldwide deal with Broadcast Music, Inc.[212]

2020–2023: Mr. Morale & the Big Steppers
On March 5, 2020, Lamar and Dave Free launched the creative entity PGLang, which was described at the time as a multilingual, artist-friendly service company.[213][214] In October, he signed a worldwide administration agreement with Universal Music Publishing Group.[215] Lamar announced through an August 2021 blog post that he was in the process of producing his final album under TDE, confirming rumors that emerged last year that he would be leaving to focus on PGLang.[216][217] The following week, he appeared on Baby Keem's single "Family Ties", which won Best Rap Performance at the 64th Annual Grammy Awards.[218][219] Lamar made additional contributions to Baby Keem's album The Melodic Blue by providing background vocals and appearing on the song "Range Brothers".[220] In November, he held a "theatrical exhibition of his musical eras" during his second headlining performance at Day N Vegas,[221][222] and featured on Terrace Martin's album Drones.[223] He co-headlined the Super Bowl LVI halftime show alongside Dr. Dre, Snoop Dogg, Eminem, 50 Cent, and Mary J. Blige on February 13, 2022, which won the Primetime Emmy Award for Outstanding Variety Special (Live).[224][225]

After releasing the promotional single "The Heart Part 5",[226][227] Lamar's fifth album, Mr. Morale & the Big Steppers, was released on May 13, 2022.[228] The double album drew on jazz, R&B, trap, and soul influences;[229][230] Alford served as its primary narrator.[231] It was widely acclaimed by critics, who applauded Lamar's vulnerable songwriting and scope.[232] Every track from the album charted on the Hot 100; its three singles–"N95", "Silent Hill", and "Die Hard"–debuted in the top-10.[233] Selling 295,000 units in its first week, Mr. Morale & the Big Steppers became Lamar's fourth consecutive number-one album on the Billboard 200.[234] It later became the first hip-hop album of the year to reach one billion streams on Spotify.[235]

In support of Mr. Morale & the Big Steppers, Lamar embarked on the Big Steppers Tour, which ran from July 2022 to March 2024.[236] The tour grossed $110.9 million in worldwide revenue, becoming the highest-grossing rap tour ever at the time.[237] Lamar wrote, co-directed, and executive produced the short film adaptation of the song "We Cry Together", which was released worldwide in September 2022.[238] An accompanying concert film for the tour, Kendrick Lamar Live: The Big Steppers Tour, was released in November.[239][240] Lamar won Favorite Male Hip Hop Artist at the American Music Awards, and Favorite Hip Hop Album for Mr. Morale & the Big Steppers. He received six awards at the BET Hip Hop Awards, including Album of the Year.[241][242] During the 65th Annual Grammy Awards, Mr. Morale & the Big Steppers was named Best Rap Album, while "The Heart Part 5" won Best Rap Performance and Best Rap Song.[243]

In May 2023, Lamar was featured on the standalone version of Beyoncé's single "America Has a Problem" and appeared on Baby Keem's single "The Hillbillies".[244][245] He won four awards at the BET Hip Hop Awards, and set four records in the process.[246] Lamar was featured in the documentary concert film Renaissance: A Film by Beyoncé and executive produced Baby Keem's short film adaptation of The Melodic Blue.[247][248] He quietly shed his ties with Aftermath Entertainment and signed a new direct licensing agreement with Interscope.[249]

2024–present: Feud with Drake, GNX, Grammy wins and Super Bowl LIX halftime show
Further information: Drake–Kendrick Lamar feud § 2023–2024: Escalation, and GNX (album)
Lamar's conflict with Drake re-escalated in March 2024 with his surprise appearance on Future and Metro Boomin's track "Like That".[250] The song spent three consecutive weeks atop the Billboard Hot 100, becoming Lamar's third number-one single and his first song to debut at the top spot.[251] From April to May, he released the Drake-aimed diss singles "Euphoria",[252] "6:16 in LA",[253] "Meet the Grahams",[254] and "Not Like Us"; all of which were either positively received or acclaimed by critics.[255] The latter installment marked the first rap song to lead the Hot 100 with a limited tracking week.[256] A celebratory one-off concert, titled The Pop Out: Ken & Friends, was held on Juneteenth.[257] "Not Like Us" went on to win five awards at the 67th Annual Grammy Awards on February 2, 2025: "Record of the Year", "Song of the Year", "Best Rap Performance", "Best Rap Song" and "Best Music Video".[258]

Lamar released "Watch the Party Die" to his Instagram account in September.[259] On November 22, he shared a song titled "GNX", exclusively on YouTube, followed with a surprise release of the album of the same name on streaming the same day.[260][261] On December 17, he released a song called "Money Without Me" on YouTube, rumored to be from Section.80 sessions. In December, he had a guest appearance on SZA's Lana, the deluxe reissue to SOS (2022). Billboard listed Lamar as the greatest pop star of 2024, highlighting his "new releases or revelations that captured headlines and captivated the culture".[262] Outside of music, Lamar starred in the animated biographical film Piece by Piece (2024).[263]

On February 9, 2025, Lamar performed at the Super Bowl LIX halftime show. His show also featured cameos and musical performances from SZA, Samuel L. Jackson, Serena Williams, and Mustard.[264][265][266] His halftime show broke viewership records, becoming the most-watched Super Bowl performance of all time with 133.5 million viewers, surpassing for the first time Michael Jackson's 1993 Super Bowl XXVII halftime show.[267] He signed on to produce a comedy feature with Free, Trey Parker and Matt Stone for Paramount Pictures, which is slated to be released on July 4, 2025.[268][269] On February 17, Lamar became the ninth overall artist and first rapper ever to reach over 100 million monthly listeners on Spotify.[270]

Personal life
Lamar began dating his fiancée Whitney Alford when they were in high school. Lamar announced his engagement to Alford in April 2015.[271][272] They welcomed their first child, Uzi, on July 26, 2019.[273][274] The couple used the cover art for Mr. Morale & the Big Steppers to announce the birth of their son, Enoch, in 2022.[275][276]

Lamar is a teetotaler[277] and lives a drug-free lifestyle.[278] In an October 2012 interview, he stated that he once tried marijuana, but the blunt had been laced with Angel Dust and he has not used any drugs since.[277] In an interview with Starz, Lamar stated he asked to play a drug abuser on the TV series Power, saying: "[Laces] is just a character that I know. I know so well, just growing up in Compton. You grow this type of love for them, you know, in this weird kind of way. You know, you don't want to see nothing happen to them, but you know he's dangerous."[279]

Artistry
Influences

Lamar considers Tupac Shakur to be his biggest influence.
Tupac Shakur is Lamar's biggest influence, having impacted both his professional and personal lives.[280] One of his earliest childhood memories is watching him and Dr. Dre film the second music video for their single "California Love" with his father at the Compton Swap Meet.[11] Lamar has described himself as an "offspring" of Shakur's artistry and sociopolitical views.[281] Although some publications have regarded him as the Shakur of his generation,[282][283] he has strived to maintain his individuality.[284]

Shakur's The Don Killuminati: The 7 Day Theory (1996), The Notorious B.I.G.'s Life After Death (1997), and DMX's It's Dark and Hell is Hot (1998) influenced Lamar's artistic direction: "I don't look at these albums like just music; it sounds like an actual film."[285] He also listened and took influence from Mos Def and Snoop Dogg during his childhood,[286] and said, "I wouldn't be here today if it wasn't for Eazy-E."[287] 50 Cent's mixtape success inspired Lamar to become an independent artist,[5] while his view on being categorized as a conscious rapper, "Yeah, I'm a conscious artist because I have a conscience", gave him a sense of perspective.[288]

Prodigy of Mobb Deep was a key influence on Lamar's earlier mixtapes,[289] while his rapping technique was stemmed from Lil Wayne and his longevity.[290] Eminem and his album The Marshall Mathers LP (2000) introduced him to songwriting elements, such as ad-libs, and impacted his aggressive approach to records such as "Backseat Freestyle".[291][292][293] He took inspiration from N.W.A's tenacity of representing his hometown with "courage, honesty and artistic brilliance".[294] Various R&B and soul artists, including Marvin Gaye,[295] the Isley Brothers,[295] Michael Jackson,[296] Teddy Pendergrass,[297] Sade, and Anita Baker, have influenced Lamar.[298] He performed with Prince, who impacted his vocal register,[299] at Paisley Park to celebrate the release of the latter's 2014 albums Plectrumelectrum and Art Official Age, which GQ described as "five minutes of brilliant insanity".[300] To Pimp a Butterfly was influenced by the works of jazz trumpeter Miles Davis and funk collective Parliament-Funkadelic.[301]

Musical style
The nature of Lamar's musical style has been described as "anti-flamboyant, interior and complex."[302] He is rooted in West Coast hip hop,[303] and has continually reinvented his sound by branching out into other genres.[304] Due to his contributions to its audience growth, through his appeal to mainstream listeners, music critics generally categorize Lamar as a progressive rap artist.[305] He suggests that his music is genreless, explaining in a 2012 interview, "You really can't categorize my music, it's human music."[306] PopDust opined that during the 2010s, a decade that was arguably defined by hip hop, Lamar constantly pushed the boundaries of what the genre could be.[307]

Lamar did not care for music production during the beginning of his career.[308] However, as he placed an emphasis on songwriting and "making material that's universal", he grew more exacting and adventurous with his compositions.[308] He is heavily involved with every aspect of his production process, including the mixing and mastering stages, and is known for working long hours in the recording studio.[309] "You gotta be hands on and know the different sounds and frequencies," Lamar explained to Variety.[308] "What makes people move, what melodies stick with you, taking the higher octaves and the lower octaves and learning how to intertwine that in a certain frequency, how to manipulate sound to your advantage."[308] Lamar chooses to work with a close-knit team of musicians, rather than constantly seek high-profile talent.[45] He has been working with his longtime producer, Sounwave, since his 2009 self-titled EP.[28]

Kendrick Lamar marked a pivotal change in Lamar's artistry. Unlike his earlier mixtapes, which consisted of freestyles over CHR and urban radio singles, the EP incorporated melancholic and "doleful" original production that emphasized his lyrics.[28] Austere jazz production was blended with alternative rap styles on Section.80,[310] with instrumentals drawing from R&B, boom bap, psychedelia, and downtempo.[311] Good Kid, M.A.A.D City abandoned the tastes of contemporary hip hop by exploring a subtle, atmospheric side of West Coast hip hop and gangsta rap.[312][313] To Pimp a Butterfly is an amalgamation of genres synonymous with African-American music, most prominently jazz, funk, and soul.[314][315] It redefined jazz rap by highlighting improvisation and soloing rather than primarily using sampling.[316][317] Minimalist arrangements are incorporated in Damn and Mr. Morale & the Big Steppers.[318][319] Damn appealed to mainstream listeners through its pop and R&B-influenced production,[320] while the scattered and distorted instrumentals of Mr. Morale & the Big Steppers was designed to make listeners feel anxious and uncomfortable.[321] GNX was an homage to the West Coast, with g-funk synths, West Coast-inspired beats and flows, and features from various underground Los Angeles rappers such as Hitta J3, YoungThreat, Peysoh, Lefty Gunplay, Wallei the Sensei, and Siete7x.[322]

Voice
Several media outlets consider Lamar to be the greatest and most important rapper of his generation.[323][324] Billboard, Forbes and Vibe named him the second-greatest rapper of all time, behind Jay-Z.[325][326] Described as a "blazing" technical rapper and "relentless searcher" by The New York Times,[302] Lamar's "limber, dexterous" flow switches from derivative to generative metrics,[327][328] while incorporating internal and multisyllabic rhyme schemes.[329] His rhymes are typically manipulated within common time, allowing him to subtly control his metrical phonology and suggest formal ambiguities similar to pop and rock repertoires.[329] Some of his rhyme manipulations feature "flexible" new school styles evoking the 1990s, while others use "rigid" old school elements recalling the 1980s.[329] Lamar frequently uses syncopation in his melodies to create contradictions between his lyrical content and rhythms.[330] With Good Kid, M.A.A.D City, he liberally plays with pronunciation, inflections, and delivery to mirror the album's emotional range.[331]

Lamar possesses a versatile tenor vocal range[332][333] and a raspy, half-shout timbre, where "his throat sounds dry and his mouth sounds wet."[334] André 3000 was the first rapper that introduced him to singing sensibilities in hip hop,[335] and he writes melody-driven songs as practice for his albums.[335] Lamar became comfortable with his vocals over time, to the point where he feels confident enough to create singing-based albums.[336] Pitchfork noticed how his harmonies on To Pimp a Butterfly never made him sound alone throughout his "desolate" performance; comparing his vocal layering to "standing in the middle, unnoticed, of a large quarrelsome crowd."[337]

Praised for his willingness to use his voice as an instrument,[338] Lamar adopts different cadences, tones, modulations, and timbres to suggest conflicting personalities, paint distinct emotions, and communicate stories using characters and personas.[339][340] His falsetto register, which he calls the "ghetto falsetto",[335] has been likened to Curtis Mayfield's.[341] MTV writes that by manipulating his voice, Lamar calls back to a lineage that runs through James Brown's foundational work in the 1960s, 1970s psychedelia, Prince's "sweaty" phantasmagoria in the 1980s, and 1990s gangsta rap.[342] He was ranked the tenth-best solo singer of the 21st century by The Times in 2023.[343]

Songwriting
Further information: List of songs recorded by Kendrick Lamar
Martin Scorsese at the 60th Berlinale in 2010
Quentin Tarantino in Paris in 2013
Several publications have compared Lamar's songwriting to Martin Scorsese (left) and Quentin Tarantino's (right) screenplays.
Branded as a "master of storytelling" by The New Yorker,[340] Lamar has been referred to as one of the greatest lyricists in modern hip hop by several publications and his peers.[344][345] Pharrell Williams suggests that what makes his songwriting stand out is because he "knows how to be very disciplined with a subject matter, he knows that stickiness is important, and he knows that it has to be great."[346] American Songwriter notes that for as much as Lamar is a musician, lyricist, and emcee, he is also "a playwright, a novelist, a short story author. He's literary within the art form of music."[347] Lamar's reflective narrative songwriting pulls from a wide range of literary and cinematic techniques, such as hip hop skits and voice-overs, to allow his audience to follow internal and external storylines.[348] His fusion of various film styles and his sonic influence has elevated his works to be some of the most "consistently poignant" in hip hop, and promoted the advancement of the narrative device.[348]

Lamar, who self-identifies as a musician and writer,[156] begins his songwriting process with an assortment of premeditated thoughts that he jotted down over the course of one year.[349] His personal experiences are a common source of inspiration, but he also pulls ideas from meeting new people, traveling, and experiencing different cultures.[349] A devout Christian, he additionally shares his spiritual triumphs and struggles on his songs.[350][351] He is an avid note-taker, and has developed keywords, phrases, and sounds to help him "trigger the exact emotions" he felt when writing the initial demo.[349] Considered to be a "radio-friendly but overtly political rapper" by Pitchfork,[352] and a populist by The Wall Street Journal,[353] Lamar's songwriting regularly infuses political criticism and social commentary concerning African-American culture.[354] Common themes explored include racial inequality, institutional discrimination, and black empowerment.[355] Lamar's critiques has been compared to the State of the Union Address by The Guardian,[356] while Billboard described it as "Shakespearean".[357] HuffPost opined that his work is a "great" piece of journalism because it "speaks from the prerogative of black communities facing oppression and directly attacks the institutions responsible for their pain," an achievement most reporters cannot attain.[358]

Lamar tries to carry a conceptual idea inside of his music, "whether it's a big concept or it's so subtle you can't even tell until you get to 20 listens."[308] Fans and publications have theorized that his albums are related to different forms of mass media.[359] Section.80 is regarded as a short story collection inspired and themed around events that impacted the millennial generation, such as Ronald Reagan's presidency.[360][361] The nonlinear narrative structure of Good Kid, M.A.A.D City is billed as a coming-of-age short film that chronicles Lamar's harsh teenage experiences in his native Compton.[362][363] Its cinematic scope has been compared to the screenplays written by filmmakers Martin Scorsese and Quentin Tarantino.[364][365] To Pimp a Butterfly unfolds as both a poem and blank letter that explores the responsibilities of being a role model and documents life as an African American during Barack Obama's presidency.[366][367] Damn is labeled as an introspective satire that explores the dualities of human nature and morality.[368][369] Mr. Morale & the Big Steppers takes on the form of a theatrical play, with confessional lyrics based on Lamar's experiences in therapy.[370][371]

Legacy

Lamar performing at the Festival Internacional de Benicàssim in 2016
Insider Inc. and CNN editors have opined that Lamar is one of the most influential musicians of the 2010s decade, deeming him a paradigm shift in contemporary hip hop and popular culture.[372][373] Throughout the Black Lives Matter movement and events following the 2016 U.S. presidential election, his work has been used as protest anthems.[374] According to American studies and media scholar William Hoynes, Lamar's progressive elements places him amongst other African American artists and activists who "worked both inside and outside of the mainstream to advance a counterculture that opposes the racist stereotypes being propagated in white-owned media and culture."[375] Matt Miller of Esquire opined that in recent years Lamar revived music videos as a form of social commentary.[376]

Lamar's music has consistently garnered critical acclaim, commercial success, as well as support from artists who have paved the way for his advancement.[377][378] His Pulitzer Prize win was considered a sign of the American cultural elite formally recognizing hip hop as a "legitimate artistic medium".[379] Senior artists such as Nas,[380] Bruce Springsteen,[381] Eminem,[382] Dr. Dre,[383] Prince,[384] and Madonna have praised his musicianship.[385] David Bowie's final album, Blackstar (2016), was inspired by To Pimp a Butterfly, and its producer Tony Visconti praised Lamar as a "rulebreaker" in the music industry.[386][387] Pharrell Williams called him "one of the greatest writers of our times" and likened him to Bob Dylan.[388] Lamar has also been cited as a strong influence on the works of various modern artists,[389] including BTS,[390] Dua Lipa,[391] Tyler, the Creator,[392] Roddy Ricch,[393] and Rosalía.[394] Lorde regards him as "the most popular and influential artist in modern music."[395]

Public image
See also: Drake–Kendrick Lamar feud
Lamar maintains a low public profile,[396] and is known to be reserved. He is reluctant to publicly discuss his personal life and generally avoids using social media.[397][398] He is also decisive when engaging with mainstream media outlets, although journalists have complimented his "Zen-like" calmness and down to earth personality.[399][400] According to Lamar, he has become "so invested in who I am outside of being famous, sometimes that's all I know. I've always been a person that really didn't dive too headfirst into wanting and needing attention. I mean, we all love attention, but for me, I don't necessarily adore it."[401] His lyrics have been a topic of media scrutiny, leading to both praise and controversy.[15][402][403]

Lamar's public perception has also been influenced by the various rap feuds he has been involved with.[404][405] Although some journalists declared him the winner of his highly publicized conflict with Drake,[406] some felt that his victory was pyrrhic due to the severity of accusations introduced and the spread of online misinformation.[407][408] Following the release of Good Kid, M.A.A.D City, media outlets have described Lamar as the "modern hip hop messiah".[409] Some critics dislike his "grating" political infusions,[410] causing him to be viewed as having a savior complex.[411][412] However, Lamar has declared himself to be the "greatest rapper alive" due to his personal connection to hip hop.[413] "I'm not doing it to have a good song, or one good rap, or a good hook, or a good bridge," he explained to Zane Lowe. "I want to keep doing it every time, period. And to do it every time, you have to challenge yourself and you have to confirm to yourself—not anybody else, confirm to yourself that you're the best, period. [...] That's my drive and that's my hunger, I will always have."[414]

Other ventures
Entrepreneurship
Lamar has been described as an "authentic" businessman who takes "calculated steps to establish his brand from the ground-up" and leaves nothing to chance.[415] He approaches traditional album rollouts with an unorthodox method, using Easter eggs and leaving cryptic messages.[416] Before releasing a studio album, Lamar shares a promotional single taken from "The Heart", a timestamp song series designed to "observe the beating pulse behind his music."[417] The vulnerable themes explored on the non-album singles have strengthened his relationship with his "inquisitive" fanbase known as Kenfolk.[417][418] His real estate portfolio includes properties in California and New York.[419][420] In 2011, Lamar crafted an original song with record producer Nosaj Thing to promote Microsoft's Windows Phone in 2011.[421] He starred alongside DJ Calvin Harris and singer Ellie Goulding in a marketing campaign for Bacardi in 2014.[422]

As a minority shareholder of TDE, Lamar was set to serve as the executive producer for the label's film division.[30] He partnered with American Express on advertising campaigns for Art Basel and Small Business Saturday,[423] and is an angel investor of the music creation platform EngineEars.[424] Lamar has also partnered with several fashion designers and outlets. As a brand ambassador, he was involved with designing sneakers for Reebok and Nike, Inc.[425][426] He developed working relationships with Grace Wales Bonner and Martine Rose; through their respective eponymous brands, they have dressed him for several public events.[427] For her Autumn/Winter 2023 collection, Twilight Reverie, Lamar worked with Bonner to create the show's soundtrack with Sampha and Duval Timothy.[428][429] Through PGLang, he composed the score and co-designed the stage for Chanel's Spring/Summer 2024 haute couture collection.[430]

Philanthropy and activism
A supporter of the Black Lives Matter movement, Lamar is a vocal advocate for racial equality.[431] In 2012, he commended Frank Ocean for coming out.[432] Lamar developed a strong friendship with former US president Barack Obama, having worked on a promotional video for Obama's My Brother's Keeper initiative.[433][434] He was critical of Donald Trump's first presidency and the U.S. Supreme Court's landmark decision to overturn Roe v. Wade.[435][436]

Lamar has headlined charity concerts benefitting local and international non-profit organizations.[437][438] He donated to the American Red Cross in November 2012 to support victims of Hurricane Sandy.[439] In December 2013, Lamar donated $50,000 to his alma mater, Centennial High School, in support of its music department.[440] He embarked on a small concert tour in 2014, and donated all of the revenue to Habitat for Humanity and his hometown.[441] In July 2017, Lamar purchased a wheelchair-accessible van for a quadriplegic fan.[442][443] He has regularly performed at TDE's annual holiday toy drive at Nickerson Gardens,[444][445] and organizes his own toy drive in Compton.[446] He joined a peace walk in June 2020 to protest against the murders of George Floyd and Breonna Taylor.[447][448] In June 2024, Lamar spearheaded a $200,000 donation to 20 charities and community initiatives based in Los Angeles.[449]

Achievements
Further information: List of awards and nominations received by Kendrick Lamar

Lamar (left) at the 2016 White House Independence Day celebration with President Barack Obama (center) and singer Janelle Monáe (right)
Throughout his career, Lamar has won 22 Grammy Awards (the third-most by a rapper in history),[450][451][452] a Primetime Emmy Award,[453] four American Music Awards,[454] 37 BET Hip Hop Awards (the most won by any artist),[455] 11 MTV Video Music Awards (including two Video of the Year wins),[456] 7 Billboard Music Awards,[457] and a Brit Award.[458] As a songwriter, he has received nominations for an Academy Award and a Golden Globe Award.[459][460] At the 58th Annual Grammy Awards, Lamar received the most Grammy nominations by a rapper in one night, with 11.[461][143] During the 65th ceremony, he became the first artist from any genre to be nominated for Album of the Year with four consecutive lead studio albums since Billy Joel (1979–1983).[462]

Lamar has appeared in various power listings. In 2015, he was featured on Ebony's Power 100 list that honors leaders within the African American community.[463] Time included him on its annual list of the 100 most influential people in the world in 2016.[464] He has appeared on Forbes' Celebrity 100 ranking (2019),[465] and its 30 Under 30 list twice in the music category (2014 and 2018).[466][467] Lamar was included twice in Billboard's lists of the greatest rappers of all time (2015 and 2023).[468][469] Complex named him the best rapper alive thrice (2013, 2017 and 2024),[470][471] and included him in their list of the 20 best rappers in their 20s thrice (2013, 2015, and 2016).[472] In May 2015, Lamar was declared a generational icon by the California State Senate for his contributions to music and philanthropy.[473] He was a grand marshal for the Compton Christmas Parade,[474] and was presented with the key to the city of his hometown for representing its evolution.[475] He served as Compton College's surprise commencement speaker on June 7, 2024.[476] Lamar is the fifth man to appear solo on the cover of Harper's Bazaar.[477]

Good Kid, M.A.A.D City, To Pimp a Butterfly, and Damn were featured in Rolling Stone's industry-voted ranking of the 500 greatest albums of all time and the 200 greatest hip hop albums of all time.[478][479] Good Kid, M.A.A.D City was additionally featured in the magazine's list of the 100 best debut albums of all time, and was named the greatest concept album ever.[480][481] It was named the seventh greatest album of all time by Apple Music in 2024.[482] To Pimp a Butterfly was ranked by several publications as one of the greatest albums of the 2010s decade,[483] while "Alright" was deemed the greatest hip hop song of the streaming era by Spotify.[484] As of February 2023, it is the top ranked album on the online encyclopedia Rate Your Music.[485] Damn is the recipient of the 2018 Pulitzer Prize for Music, the first time a musical work outside of the classical and jazz genres was honored.[486][487] Its tour companion, along with Big Steppers Tour (2022–2024), are two of the highest-grossing hip hop tours of all time.

"""
# source: https://en.wikipedia.org/wiki/Kendrick_Lamar

if __name__ == '__main__':
    print('Hello, LangChain!')

    summary_template = """
      given the information {information} about a person, create the following:
      1. a short summary,
      2. two interesting facts about them.
    """

    summary_prompt_template = PromptTemplate(input_variables = ['inforamtion'], template = summary_template)

    llm = ChatOpenAI(temperature = 0, model_name = 'gpt-3.5-turbo') # temperature decides how creative the model is
    chain = summary_prompt_template | llm
    res = chain.invoke(input = {"information": information})

    # Create a prompt template
    class PromptTemplate(StringPromptTemplate):
        def __init__(self):
            self.template = summary_template

            